# Generated by Django 5.2.16 on 2026-07-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ats', '0002_extractedskill'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('course_url', models.URLField(max_length=500)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration', models.CharField(blank=True, help_text='Example: 6 hours, 4 weeks', max_length=100)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='jobs.skill')),
            ],
            options={
                'ordering': ['skill__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('priority', models.PositiveIntegerField(default=1)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('ats_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to='ats.atsscore')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='courses.course')),
            ],
            options={
                'ordering': ['priority', '-recommended_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('title', 'provider', 'skill'), name='unique_course_provider_skill'),
        ),
        migrations.AddConstraint(
            model_name='courserecommendation',
            constraint=models.UniqueConstraint(fields=('ats_score', 'course'), name='unique_course_recommendation_per_score'),
        ),
    ]
