# Generated by Django 5.2.16 on 2026-07-21 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='ats.resumeanalysis')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_resumes', to='jobs.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('analysis', 'skill'), name='unique_extracted_skill_per_analysis')],
            },
        ),
    ]
